Source/Web/NewsSystem.Web/Controllers/GraphsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using NewsSystem.Data;
using NewsSystem.Common;

namespace NewsSystem.Web.Controllers
{
    public class GraphsController : BaseController
    {
        public GraphsController(NewsSystemData data)
            : base(data)
        {
        }

        public ActionResult Index(DateTime? startDate, DateTime? endDate, string criteria)
        {
            var chart = new Chart(width: 1200, height: 400);

            var allNews = this.Data.News.All();

            if (startDate != null || endDate != null)
            {
                if (endDate == null)
                {
                    endDate = DateTime.Now;
                }

                else if (startDate == null)
                {
                    startDate = GlobalConstants.DefaultStartDate;
                }

                allNews = allNews.Where(n => n.PubDate >= startDate && n.PubDate <= endDate);
            }

            switch (criteria)
            {
                case "0":
                    var mostPublishedNews = allNews
                        .OrderByDescending(n => n.CountPublications)
                        .Take(5);

                    chart.AddTitle("Top 5 published news");

                    chart.AddSeries(
                        chartType: "Column",
                        xValue: mostPublishedNews.Select(n => n.Title).ToList(),
                        yValues: mostPublishedNews.Select(n => n.CountPublications).ToList());
                    break;

                case "1":
                    var mostReadNews = allNews
                        .OrderByDescending(n => n.CountVisits)
                        .Take(5);

                    chart.AddTitle("Top 5 visited news");

                    chart.AddSeries(
                        chartType: "Column",
                        xValue: mostReadNews.Select(n => n.Title).ToList(),
                        yValues: mostReadNews.Select(n => n.CountVisits).ToList());
                    break;

                case "2":
                    var newsGroupedByCategory = allNews
                        .GroupBy(n => n.Category)
                        .Select(gr => new
                        {
                            Category = gr.Key.ToString(),
                            Count = gr.Count()
                        })
                        .OrderBy(gr => gr.Count);

                    chart.AddTitle("News by category");

                    chart.AddSeries(
                        chartType: "Pie",
                        xValue: newsGroupedByCategory.Select(n => n.Category).ToList(),
                        yValues: newsGroupedByCategory.Select(n => n.Count).ToList());
                    break;
                default:
                    return Content("<h1>Please select criteria</h1>");
            }

            var file = chart.GetBytes("png");
            return File(file, "image/png");
        }
    }
}

Source/Web/NewsSystem.Web/Controllers/HomeController.cs
using NewsSystem.Data;
using System;
using System.Linq;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using NewsSystem.Web.ViewModels;
using NewsSystem.Common;

namespace NewsSystem.Web.Controllers
{
    public class HomeController : BaseController
    {

        public HomeController(NewsSystemData data)
            : base(data)
        {
        }

        //TODO Use Cache
        public ActionResult Index(string query, DateTime? startDate, DateTime? endDate, string criteria)
        {
            var allNews = this.Data.News
                .All();

            if (!(query == null || query.Trim() == String.Empty))
            {
                allNews = allNews.Where(n => n.Title.IndexOf(query) != -1);
            }

            if (startDate != null || endDate != null)
            {
                if (startDate == null)
                {
                    startDate = GlobalConstants.DefaultStartDate;
                }
                else if (endDate == null)
                {
                    endDate = DateTime.Now;
                }

                allNews = allNews.Where(t => t.PubDate >= startDate && t.PubDate <= endDate);
            }

            if (!(criteria == null || criteria.Trim() == String.Empty))
            {
                switch (criteria)
                {
                    case "0":
                        allNews = allNews.OrderByDescending(n => n.CountPublications);
                        break;
                    case "1":
                        allNews = allNews.OrderByDescending(n => n.CountVisits);
                        break;
                    case "2":
                        allNews = allNews.OrderByDescending(n => n.Description.Length);
                        break;
                    case "3":
                        allNews = allNews.OrderBy(n => n.Description.Length);
                        break;
                    case "4":
                        allNews = allNews.OrderByDescending(n => n.CountUpdates);
                        break;
                    case "5":
                        var topCategory = allNews.GroupBy(n => n.Category).OrderByDescending(c => c.Count()).First().Key;
                        allNews = allNews.Where(n => n.Category == topCategory);
                        break;
                    default:
                        break;
                }
            }

            var allTasksModel = allNews.Project()
                .To<NewsViewModel>()
                .ToList();

            return View(allTasksModel);
        }
    }
}

Source/Web/NewsSystem.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Source/Web/NewsSystem.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Source/Web/NewsSystem.Web/Views/Home/Index.cshtml
@using NewsSystem.Data.Models;

@model IEnumerable<NewsSystem.Web.ViewModels.NewsViewModel>

@{
    ViewBag.Title = "Index";
    ViewBag.SearchQuery = Request.QueryString["query"];
    ViewBag.StartDate = Request.QueryString["startDate"];
    ViewBag.EndDate = Request.QueryString["endDate"];
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_Search")
    </div>
    <div class="col-md-9">
        @using (Html.BeginForm("Index", "Home", FormMethod.Get, new { @class = "form-inline" }))
        {
            <div class="form-group">
                <input type="text" value="@ViewBag.startDate" class="form-control date-filter datetimepicker" id="startDate" name="startDate" placeholder="Start date...">
            </div>
            <div class="form-group">
                <input type="text" value="@ViewBag.endDate" class="form-control date-filter datetimepicker" id="endDate" name="endDate" placeholder="End date...">
            </div>
            <div class="form-group">
               @Html.DropDownList("criteria", EnumHelper.GetSelectList(typeof(FilterByCriteria)), new { @class = "form-control", @name="criteria"})
            </div>
            <button type="submit" class="btn btn-primary"><small>Filter by date</small></button>
        }
    </div>
</div>
<br />

<div class="row">
    <div class="col-md-8">
        @if (Model.Count() == 0)
        {
            if (ViewBag.SearchQuery != null)
            {
                <h3>There are no tasks match your search criteria</h3>
            }

            else
            {
                <h3>No tasks</h3>
            }
        }

        else
        {
            if (ViewBag.SearchQuery != null)
            {
                <p class="text-center">Search results for "@ViewBag.SearchQuery"</p>
    <div class="panel panel-default search-results">
        <ul class="list-group">
            @foreach (var news in Model)
            {
                @Html.Partial("_NewsSimpleView", news)
            }
        </ul>
    </div>
            }
            else
            {
                <h2 class="text-center">
                    <span> All News </span>
                </h2>
                if (ViewBag.StartDate != null && ViewBag.EndDate != null)
                {
                    if (ViewBag.StartDate == string.Empty)
                    {
                        ViewBag.StartDate = "begining";
                    }
                    else if (ViewBag.EndDate == string.Empty)
                    {
                        ViewBag.EndDate = "today";
                    }
                    <div class="text-center">News between @ViewBag.StartDate and @ViewBag.EndDate </div>
                }
                <div class="vticker">
                    <ul>
                        @foreach (var news in Model)
                        {
                            @Html.Partial("_NewsSimpleView", news)
                        }
                    </ul>
                </div>
            }
        }
    </div>
    <div class="col-md-4">
        @using (Html.BeginForm("Index", "Graphs", FormMethod.Get, new { @class = "form-inline" }))
        {
            <div class="form-group">
                <input type="text" value="@ViewBag.startDate" class="form-control date-filter datetimepicker date-form" id="startDate" name="startDate" placeholder="Start date...">
            </div>
            <div class="form-group">
                <input type="text" value="@ViewBag.endDate" class="form-control date-filter datetimepicker date-form" id="endDate" name="endDate" placeholder="End date...">
            </div>
            <div class="form-group">
                @Html.DropDownList("criteria", EnumHelper.GetSelectList(typeof(GraphCriteria)), new { @class = "form-control", @name = "criteria" })
            </div>
            <button type="submit" class="btn btn-warning pull-right"><small>Show Graph</small></button>
        }
        <br />
    </div>
</div>
<div class="clearfix"></div>